# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default
#  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

# Prepare Analysis Configuration task
- task: SonarQubePrepare@4
  displayname: 'Prepare SonarQube Analysis'
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'pwc_pwc'
    cliSources: '.'

- script: |
    npm run build

# Run Code Analysis task
- task: SonarQubeAnalyze@4

# Publish Quality Gate Result task
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: pwc/simple-node-js-react-npm-app
    containerRegistry: docker_reslv_io
    command: build
    Dockerfile: Dockerfile
    tags: latest

- task: Docker@2
  displayName: Push docker image
  inputs:
    repository: pwc/simple-node-js-react-npm-app
    containerRegistry: docker_reslv_io
    command: push
    Dockerfile: Dockerfile
    tags: latest