apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node-js-react-npm-app
  template:
    metadata:
      labels:
        app: simple-node-js-react-npm-app
    spec:
      containers:
      - name: simple-node-js-react-npm-app
        image: $(containerRegistry)/$(image-name):$(tag)
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: $(imagePullSecret)
