apiVersion: v1
kind: Service
metadata:
  name: simple-node-js-react-npm-app-service
spec:
  selector:
    app: simple-node-js-react-npm-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
